### ISSUE TITLE
fix release name; merge more fixes?

### ISSUE THREAD

**Issue by notestaff** [refresh-bio/KMC#100] opened 2018-07-17 18:25 UTC
@marekkokot sorry, I suggested the wrong name for the release tag.  per https://www.python.org/dev/peps/pep-0440/ it should be 3.1.1rc1 .   it's a release candidate for the (future)  version 3.1.1, not the current 3.1.0; and version names in conda cannot have dashes.

also, maybe merge fixes #97 and #98 if these are ok?   thanks!

**Comment by marekkokot** [comment] 2018-07-17 18:37
Its done. 
I started to think about this aspect after I created this release and I was intended to check it. 
Now I don't need to, so thanks :).

**Comment by notestaff** [comment] 2018-07-17 18:49
@marekkokot https://www.python.org/dev/peps/pep-0440/ says it should be 3.1.1rc1 not 3.1.1rc.1  .  sorry for nitpicking, but these are requirements of conda/bioconda .

**Comment by marekkokot** [comment] 2018-07-17 19:05
No problem, is that OK now?

**Comment by marekkokot** [comment] 2018-11-20 07:19
I assume it was OK, and I am closing this issue. If something is wrong just reopen it and supply some more info.

**Closed by marekkokot** 2018-11-20 07:19 UTC
