### ISSUE TITLE
set all counts to a specified value

### ISSUE THREAD

**Issue by notestaff** [refresh-bio/KMC#58] opened 2018-04-12 20:44 UTC
@marekkokot Is there a way to set all kmer counts in a database to a specific value?  If not, would that be hard to add?   Use case: I have a set of samples, and a kmc kmer database for each sample.  I want to make a database that, for each kmer, records which samples have it (basically a colored de Bruijn graph).  If there are <=64 samples I can assign to kmers from sample i the count 2^i, then the sum of counts gives the set of samples .  If 64<n_samples<=128 can represent this with two kmc kmer databases per sample, etc.

**Comment by marekkokot** [comment] 2018-04-16 19:44
Hi,

It is not a lot of work, and I will try to add this functionality as fast as possible (I don't know when it will be ready, because I have something other (KMC unrelated) things to do first).

Still, there is some issue that I would like to point. 
The short story is that kmc_tools stores counters of kmers on uint32_t, so one database can be used for <=32 samples, instead of 64.

The reason is caused by the fact that KMC uses uint32_t to store counter, as it is enough for any real input data.
Long story (if you are interested):
When kmc_tools was created it inherited that trait. After that KMC was extended to support k-mers of length lower than 10, so uint32_t became unsure so in case of short k-mers we use uint64_t if needed.
Appropriate changes were not made yet in kmc_tools. I hope they will, but even if it seems to be a small change, there is a couple of things that must be validated (not only correctness of results, but if it affects running time, it will for sure affect memory consumption so depending on input databases and parameters I will probably prefer to make kmc_tools to use uint64_t only if needed).


Is uint32_t as counter enough, at least for now? If no, I will probably postpone implementing this feature, though I really like your use case.

**Comment by notestaff** [comment] 2018-04-19 19:50
Yes, uint32_t would work.  I'd just have to keep more copies of the kmer databases, which feels redundant but is doable.

One other option is if you could natively support treating counters as indices into a lookup table where actual values are stored.  Then operations on counters could be turned into operations on the referenced values.  You'd keep a hash-based map from value to index in the table, so that if an operation produces a value not yet seen, it's added to the table.   Then counters could represent sets of samples, with set operations for combining the values; but also any other type that doesn't fit into 32 bits, as long as the actual number of different values seen is under 2^32 (true for sets of samples).

**Comment by notestaff** [comment] 2018-04-20 14:01
P.S. another use case is to see, for each kmer, when in the outbreak it first appears.  I’d set each sample’s kmer counts to days since outbreak start, then take the min during union.

**Comment by notestaff** [comment] 2018-04-23 16:37
@marekkokot Is there any chance you could add the set-all-kmers-to-N functionality (with uint32) sometime in the next couple of days?  (It would help a lot for some analyses I'm preparing for this Friday).

**Comment by marekkokot** [comment] 2018-04-23 16:40
@notestaff 
Yes, there is a chance. In fact, I hoped it will be finished earlier, but unfortunately, some other things to do appeared :( I will try to implement this tomorrow, but I cannot guarantee success. I will do my best :)

**Comment by notestaff** [comment] 2018-04-23 16:49
@marekkokot Thanks so much!  I tried to see if I can do it myself but the official API is read-only.  If it's simpler for you to add an API for writing the database I can then try to implement the command myself.

**Comment by marekkokot** [comment] 2018-04-23 19:49
Hi,
I've implemented this functionality with a41e7cb6bc929831afa08564109cf211bc59d452
Please keep in mind it was not fully tested, so if you spot any bug please let me know.
Usage example:
```
bin/kmc_tools transform o set_counts 15 o15
```

**Comment by marekkokot** [comment] 2018-04-23 20:35
That is correct.

**Comment by marekkokot** [comment] 2018-05-24 09:26
@notestaff Have you used this operation, does it work as expected? If yes, I would like to close this issue.

**Comment by notestaff** [comment] 2018-05-24 09:31
@marekkokot yes, thanks a lot for adding it on short notice, it was quite helpful.   I also plan to use it in some upcoming analyses.

**Comment by marekkokot** [comment] 2018-05-24 09:32
Great, thanks!

**Closed by marekkokot** 2018-05-24 09:32 UTC
