### ISSUE TITLE
Weird kmer counting

### ISSUE THREAD

**Issue by Tinyman392** [refresh-bio/KMC#41] opened 2017-10-13 15:31 UTC
OK, so I have a little bit of an issue with KMC 3.0.1 on a Linux system.  I have multiple fasta files (let's call them F1.fasta, F2.fasta, ..., Fn.fasta) which contain multiple genes each and I ran 

```
kmc -k15 -fm -ci1 -cs1677215 F1.fasta F1.fasta temp/
kmc_dump F1.fasta F1.fasta.15.kmrs
```

This counts the 15mers within each fasta file.  I then ran

```
cat F*.fasta > all.fasta
kmc -k15 -fm -ci1 -cs1677215 all.fasta all.fasta temp/
kmc_dump all.fasta all.fasta.15.kmrs
```

This concatenates all the fasta files together and counts the 15mers in there.  Now, there are a set of 15mers that are found in the individual fasta files, let's call one of these kmer X, that isn't found in the all.fasta file.  This is kind of baffling me as it should't be possible for that to happen.  How can a kmer be found in an individual fasta file, but not when we concatenate the fasta files together?

I have a total of about 5500 fasta files and X appears in them <1 time (typically).  

To dig even further, I ran KMC 2.3.0 on the same all.fasta file and got different results.  Those results were more inline with those of the individual KMC 3.0.1 runs (X was found in the KMC 2.3.0 run).  Additionally, I should note that both KMC 2.3.0 and KMC 3.0.1 find the same number of unique 15mers, however, the 15mers that are flip flopped around (a total of 5 15mers are flip flopped) do not have the same counts.  This makes me think there may be an issue with the way a kmer is getting encoded inside the database and then getting decoded in the dump.  IE, if I decoded the DB to produce 15mer X, it wasn't X that was encoded there to begin with, rather it was some other 15mer Y (or stated differently encode(Y) = E, decode(E) = X).  In any case, something changed between 2.3.0 and 3.0.1 (possibly 3.0.0) to produce this result.  

I have the all.fasta file that was used to produce the above results.  It's 550MB in size (165MB compressed).  Github won't let me attach it here, so if you need it, please do ask (maybe I could email it to you?).

One final note, I did test this on the executable that you offer on your website (http://sun.aei.polsl.pl/REFRESH/index.php?page=projects&project=kmc&subpage=download) which is stated as 3.0.  I got the odd results which made me go and compile 3.0.1 from scratch (I didn't see an available executable on your GitHub) to have the same results.  Because of the bug that has the 3.0.1 kmc executable still printing 3.0.0 as its version, I'm not sure which version you have on your website.  But if it is 3.0.0, I did test that as well.  If not, then I did not test 3.0.0.  That said, from a user perspective, please fix that little bug with the 3.0.0 on your next release (I'm sure you have already as you closed it the request for this; from a user perspective, it's really annoying not knowing what version we're actually on).  

Any insight on this issue would be greatly appreciated!

**Comment by marekkokot** [comment] 2017-10-13 16:20
Hi, 
Thanks for reporting. 
I would really appreciate if you could send me those F1.fasta, F2.fasta ... files. Im am not sure if you still have those files as you wrote that you may send me all.fasta. If you don't have them please send me all.fasta. I would prefer separate files as I may merge them on my own and reproduce your experiment. 
Maybe you could use google drive or dropbox for that? I am not sure about limit size of received attachments on my emails providers. 
Could you also point me a exact k-mer that you denoted as X (or a list of examples of such k-mers).

Sorry for troubles with version numbering.

**Comment by Tinyman392** [comment] 2017-10-13 19:54
I do have the original files.  I'm uploading to DropBox right now.  In the meantime, I need an email, username, etc. to share the folder so you can access it.

**Comment by marekkokot** [comment] 2017-10-13 20:17
Thank you. My email: marek.koki@gmail.com

**Comment by Tinyman392** [comment] 2017-10-13 20:18
Thanks!  I shared the file with you!

**Comment by marekkokot** [comment] 2017-10-13 20:20
Thanks :), I am downloading right now, I let you know when I will check it.

**Comment by marekkokot** [comment] 2017-10-13 21:32
Hi,
Could you please point me an exact file and k-mer that is present in this files  and is not present in the database after counting for all.fasta?

I've already:
1. counted database for all.fasta using kmc compiled with newest sources on github (3.0.1)
2.a counted database for each file separately using kmc compiled with newest sources on github (3.0.1)
2.b merged these databases into one common using kmc_tools
3. Compared those databases and they are equal, so
4. I downloaded kmc3.0.0 and counted k-mers for all.fasta (it also contains exactly the same information)
5. The same but using kmc 2.3

So I am probably not able to reproduce your results.
If you want I may send you my resulting database, or you mey send my yours

I would also like to point that k-mers in databases after couple of runs may have different order (yet as a set they shold be equal). You may use kmc_tools to sort k-mers lexicographically (easier to compare databases).

**Comment by Tinyman392** [comment] 2017-10-13 23:14
OK, I went back and did a few things...  I originally had the KMC 3.0.1 run on a different machine than the KMC 2.3.0.  Machine 1 has access to KMC 2.3.0 (compiled on machine 1) and the KMC 3.0.1 (compiled on machine 2) on machine 2 while machine 2 only has access to KMC 3.0.1.  I was assuming that they would spit out the same results...  I was terribly mistaken.  

With machine 1, KMC 2.3.0 and KMC 3.0.1 both return the same results on the allFasta.fasta.  It's specifically with machine 2 that I'm having issues then.  It was originally on Machine 2 where I had 3.0.0 finding 15mers in the individual fasta files that were not in the catted one.  There is something really weird going on, I think it may be hardware related.  

That said, I'm going to do more digging on machine 2 (where I originally saw the issue) when I return to work on Monday (home internet is being glitchy right now and giving me a headache).

**Comment by marekkokot** [comment] 2017-10-14 08:05
The results on both machines should be the same, so its really wired. Maybe there is some issue with your machne 2, or maybe there is some issue with KMC on that machine. Could you specify your hardware configuration on machine 2, especially amount of RAM and porcessor(s) details?

**Comment by Tinyman392** [comment] 2017-10-16 15:09
OK, I'm unable to run anything on machine 2 for the time being due to it being busy with something, I've since tried running on a third machine (very similar to the second) and got different results as well.  I was hoping machine 2 would be free by now, but I'll have to wait until Wednesday to try some things out.  I've also consulted my IT admin regarding the issue and he's going to try remounting the drive as NFS 3 on machine 2 or 3 (both machine 2 and 3 are currently busy) as soon as it's free.  

Here are the processor, RAM, OS, and mounting (drive I'm using is a network file system drive) details for the three machines I've since tested on:

- Machine 1: Intel(R) Xeon(R) CPU E5-2620 0, RAM: 264505400 kB, CentOS Release 6.9 (final), NFS 3
- Machine 2: Intel(R) Xeon(R) CPU E5-4669 v4, RAM: 1585224152 kB, Ubuntu 16.04.3 LTS (Xenial Xerus), NFS 4
- Machine 3: Intel(R) Xeon(R) CPU E5-4669 v4, RAM: 1585224876 kB, Ubuntu 16.04.2 LTS (Xenial Xerus), NFS 4

Machine 1 produces the correct output for KMC 2.3 and KMC 3.0.1.  Machine 2 and 3 haven't been tested with KMC 2.3 yet, but both produce different results on KMC 3.0.1 (even from each other, they were run 12 hours apart).  I think it is possible that there is a bug causing the machines to read a cached temp file instead of the new one generated causing some issues.  The other thing I'm going to try is running it in RAM only mode (-r option).

**Comment by marekkokot** [comment] 2017-10-16 15:27
Thanks for reporting. Let me know after trying with -r switch (for some small data there will be for sure enough RAM).

One more thing came to my midn. Maybe you are running multiple KMC instances simultaneously with the same temp directory, if yes this is probably the cause and you should use separate directories for each KMC instance.

**Comment by Tinyman392** [comment] 2017-10-16 16:09
The KMC instances are being run sequentially, so there are no multiple KMC runs simultaneously, so that wouldn't cause an issue.  

At this point, I'm sandboxing all current runs just to be safe.  I'm running KMC 2.3 and KMC 3.0.1 on each machine right now.  I'll report back soon.  Note that at this point I'm only running KMC on the allFasta.fasta file.  

So machine 2 is very busy right now, so I got KMC 3.0.1 and KMC 2.3 to run on both machine 1 and machine 3.  Here are the results:
- Machine 1: KMC 2.3 and KMC 3.0.1 produce the same exact results
- Machine 3: KMC 2.3 and KMC 3.0.1 produce different results.  The results of KMC 2.3 matches the results of those from machine 1.  

On another note, one weird thing that keeps cropping up is that KMC 3.0.1 takes much longer to run machine 2 than it does on machine 1, which doesn't seem to make much sense (machine 2 has a total of 176 cores, machine 1 has 24, that and the RAM differences).

**Comment by marekkokot** [comment] 2017-10-16 16:31
Ok, wow that's a lot o cores. Could you also try to run KMC3.0.1 specifying lower number of threads (e.g. 8) with -t switch? Maybe for some reason that I cannot imagine right now it is a cause. We have never run KMC with that many threads.

**Comment by Tinyman392** [comment] 2017-10-16 17:22
The lower number of threads fixed the issue.

**Comment by marekkokot** [comment] 2017-10-16 20:55
Thanks. I need to admit that currently I have absolutely no idea what is going on. I've tried repeat counting on machine with 64 cores (I don't have access to machine with more corres) and the result is OK. As default KMC gets all avaiable cores. I have run KMC with higher number of threads (768) which is not optimal for performance when the number of cores is only 64 but I hoped it will cause the same issue that occurs on your machine, unfortunately it doesn't.

You mentioned that the running time is longer when using all cores, could you please specify the running times of both stages that are a part of KMC report? 

I am afraid that it will be extremely hard to fix this issue as I cannot reproduce your results. I have only a little suspicions which part of code may cause that bug, but it is not enough and I will for sure need to dig a little deeper, which is currently not possible. I wouldn't feet right about asking you to perform more experiments. Anyway thanks for reporting this issue, I will ask in my department if we have any machine with higher number of cores.

**Comment by marekkokot** [comment] 2017-10-17 09:09
Hi, OK I am probably able to reproduce this issue on machine with XEON processor (it has lower number of cores but when I specify 176 threads the second stage of KMC is really slow). I will try to fix this issue.

**Comment by Tinyman392** [comment] 2017-10-17 13:59
Awesome, I'm glad you are able to reproduce that portion of the bug.  Did this also reproduce the different 15mer issue or just speed?

**Comment by marekkokot** [comment] 2017-10-17 19:24
Both, speed and incorrect result. For now it seems that those bugs are independed which seems unlikely, so it is probably quite complicated... Interestingly it occurs with 176 threads, but with 175 and 177 it works well, for 352 threads it fails again, and on other machine I wasn't able to reproduce the issue. 
I will work on it, for now you may just specify lower number of threads.
Thanks again for reporting that.

**Comment by Tinyman392** [comment] 2017-10-17 19:39
352 = 176*2; I'm curious, does it fail with 88?

**Comment by marekkokot** [comment] 2017-10-17 19:55
I know, this is why I checked this number of threads. On 88 result is OK (also for 44, 22, 11), on 704  result is OK (but there is strange freeze between stages, but is is acceptable). I will dig further.

**Comment by marekkokot** [comment] 2017-10-21 14:54
Hi, could you try if  f5bca2db9c202a2ab7961f9e05797f9c43b61e96 fixes the problem?

**Comment by Tinyman392** [comment] 2017-10-26 16:01
Hey,

Sorry for the late reply, lots of stuff going on.  I clone the repository and compiled the code and reran both KMC2 (which worked on all machines before) and KMC3 (with the f5bca2d fix) and it produces the same result without needing to specify thread count!  Glad you can figure out the bug!  

Thanks for the help and support; it's much appreciated!

**Comment by marekkokot** [comment] 2017-10-26 17:34
Hey,

Thanks for info and thanks again for reporting that bug.

**Closed by marekkokot** 2017-10-26 17:34 UTC
Labels: bug
