### ISSUE TITLE
Possible bugs in multiline FASTA parsing

### ISSUE THREAD

**Issue by jamshed-k** [refresh-bio/KMC#151] opened 2020-07-14 03:05 UTC
Hello @marekkokot, thanks a lot for the awesome library. A small concern to note -- recently, @rob-p and I discovered that KMC might produce databases with some _k_-mers missing, based on the input file format, while the different files contain essentially the same sequences. For example, these are three datasets that all contain essentially the same content: i) a multiline-FASTA ([GRCh38_fixed_unitigs.fa](https://drive.google.com/file/d/1AptwhszTYc6PWEBa6HpdtZzeuYBhKL7X/view?usp=sharing)), ii) an 80-characters max multiline-FASTA ([GRCh38_fixed_unitigs_folded.fa](https://drive.google.com/file/d/1BpTuiuAzsRm41LCG8mdWsMDuCkU-QtSW/view?usp=sharing)), and iii) a FASTQ ([GRCh38_fixed_unitigs.fq](https://drive.google.com/file/d/1ddJoupRoqeJSL7-cdLk7YGU80xzrnxOw/view?usp=sharing)). Note that, these files contain unitigs produced from some algorithm using `k = 31`, and hence each 31-mer occurs exactly once throughout. It's been verified that the unitigs contain a total of `2652229049`  _k_-mers, all being unique. The verification has been done manually, and also using Jellyfish and DSK. Running KMC on these three files produces different numbers of total (and unique) _k_-mers:
​
1. For the multiline-FASTA: `kmc -k31 -fm -ci0 -t16 ./GRCh38_fixed_unitigs.fa ./temp/temp.res ./temp/`
​
```
Stats:
   No. of k-mers below min. threshold :            0
   No. of k-mers above max. threshold :            0
   No. of unique k-mers               :   2652229046
   No. of unique counted k-mers       :   2652229046
   Total no. of k-mers                :   2652229046
   Total no. of sequences             :     35778433
   Total no. of super-k-mers          :    244814131
```
​
2. For the folded-FASTA (using [seqtk](https://github.com/lh3/seqtk)): `kmc -k31 -fm -ci0 -t16 ./GRCh38_fixed_unitigs_folded.fa ./temp/temp.res ./temp/`
​
```
Stats:
   No. of k-mers below min. threshold :            0
   No. of k-mers above max. threshold :            0
   No. of unique k-mers               :   2652229047
   No. of unique counted k-mers       :   2652229047
   Total no. of k-mers                :   2652229047
   Total no. of sequences             :     35778433
   Total no. of super-k-mers          :    244814127
```
​
3. For the FASTQ: `kmc -k31 -fq -ci0 -t16 ./GRCh38_fixed_unitigs.fq ./temp/temp.res ./temp/`
​
```
Stats:
   No. of k-mers below min. threshold :            0
   No. of k-mers above max. threshold :            0
   No. of unique k-mers               :   2652229049
   No. of unique counted k-mers       :   2652229049
   Total no. of k-mers                :   2652229049
   Total no. of reads                 :     35778433
   Total no. of super-k-mers          :    244814124
```
​
We're using [the latest commit](https://github.com/refresh-bio/KMC/commit/477ddb02d0cc512f8c14e27743d922bf902ef874), but observed the same behavior using the latest release. It would be great if you may have a look into the issue!  Speculatively, since all the numbers seem correct when reading from FASTQ input, it seems possible (likely?) that the result is related to the parsing of non-FASTQ input files.

**Comment by marekkokot** [comment] 2020-07-14 11:59
Hi,

thanks for reporting this bug. In fact, there is also -fa switch which is dedicated for fasta (not multilined) and it seems it works, so the problem is in parsing with -fm. I will try to fix it as soon as possible.

This is really nicely reported bug, that I can easily reproduce, so thanks for such a good and detailed description.

**Comment by marekkokot** [comment] 2020-07-16 10:30
Hi,
sorry, there were some other important things to do :(
I am afraid I will not be able to take a look at why the results are incorrect in the next several days.

**Comment by jamshed-k** [comment] 2020-09-04 23:06
Hello @marekkokot, no rush; but it would be great if you could have a look into this bug sometime!

Regards!

**Comment by marekkokot** [comment] 2020-09-06 17:52
Hello @jamshed-k 

sorry for the long delay. I hope the last commit correctly fixes this bug. I verified this on your files and it seems to work.
I would really appreciate if you could verify it as well and if it works correctly then please close this issue.
In case of any further problems/bugs please let me know.
Thanks for your patience.

Regards.

**Comment by jamshed-k** [comment] 2020-09-07 04:01
Hello @marekkokot,

Yes, the patch seems to work for these files and are producing same results. Thanks a lot for the fix!

Regards.

**Closed** 2020-09-07 04:01 UTC
Labels: bug
